// Code generated by mockery v2.42.2. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// HandlerResult is an autogenerated mock type for the HandlerResult type
type HandlerResult struct {
	mock.Mock
}

// NewHandlerResult creates a new instance of HandlerResult. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandlerResult(t interface {
	mock.TestingT
	Cleanup(func())
}) *HandlerResult {
	mock := &HandlerResult{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
